### ISSUE TITLE
"Failed to parse balance: TypeError: Cannot read property '0' of null"

### ISSUE THREAD

**Issue by reedlaw** [slashdotdash/node-ledger-rest#1]
Using Ledger 3.1.0-20141005 on Arch Linux I get this error for both the /balance and /register endpoints.

**Comment by bruny** [comment]
This occurred for me with 3.1.1-20160111

**Comment by bruny** [comment]
For me at least, this appears to be due to journal entries missing commodity value, e.g.:

2015/06/30 Opening Balance
    Equity:Opening Balance  $1000
    Assets:Bank -$1000
works, however
2015/06/30 Opening Balance
    Equity:Opening Balance  1000
    Assets:Bank -1000
doesn't.

There is a ledger mailing list here that has more information about the implications of not specifying commodities in journal entries: https://groups.google.com/forum/#!topic/ledger-cli/MojlS_l3xxU/discussion

**Comment by slashdotdash** [comment]
The `ledger-cli` library that this uses may not be handling missing currency for transactions. I probably assumed that the currency would always be present for each transaction within the ledger file.

**Comment by bruny** [comment]
It's fixed in the ledger-cli library with the following commit: https://github.com/slashdotdash/node-ledger/commit/8acbe75e8578a1be11a8011f96cbd99ad67fdffd

Would a bump of the version dependencies get the most up-to-date version of ledger-cli?

**Comment by slashdotdash** [comment]
@bruny Good spot on that fix. 

I need to bump the version number of `ledger-cli`, publish it to npm and then use the updated version here.

**Comment by slashdotdash** [comment]
I've published version 0.2.0 or `ledger-cli` to npm. Then I have upgraded `ledger-rest` to use it and also published to npm.
